// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.tjq.netty.proto;

public interface MResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.tjq.netty.proto.MResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string realname = 2;</code>
   */
  java.lang.String getRealname();
  /**
   * <code>string realname = 2;</code>
   */
  com.google.protobuf.ByteString
      getRealnameBytes();
}
